title: Mesith Rathnayake
description: >-
  Computer Engineering undergraduate | Embedded systems, Web development & AI enthusiast.
baseurl: ""
url: "https://mesith-rathnayake.github.io"

remote_theme: cotes2020/jekyll-theme-chirpy

github_username: mesith-rathnayake
linkedin_username: Mesith Rathnayake
email: mesithrathnayake0930@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag
